# Generated by Django 4.1.2 on 2022-10-08 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название СМИ')),
                ('url', models.URLField(max_length=255, verbose_name='Ссылка на СМИ')),
                ('logo', models.URLField(verbose_name='Ссылка на логотип СМИ')),
                ('rss_url', models.URLField(verbose_name='RSS поток')),
            ],
            options={
                'verbose_name': 'СМИ',
                'verbose_name_plural': 'СМИ',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название роли в компании')),
            ],
            options={
                'verbose_name': 'Роль в компании',
                'verbose_name_plural': 'Роли в компиниях',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255, verbose_name='Название тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Artilce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок статьи')),
                ('img', models.URLField(blank=True, null=True, verbose_name='Фотография статьи')),
                ('description', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Краткое описание статьи')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Текст статьи')),
                ('category', models.IntegerField(blank=True, null=True, verbose_name='Какой роли относится статья')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.media', verbose_name='СМИ')),
                ('tags', models.ManyToManyField(to='news.tags', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
