# Generated by Django 4.1.2 on 2022-10-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Роль в компании', 'verbose_name_plural': 'Роли в компаниях'},
        ),
        migrations.AddField(
            model_name='artilce',
            name='inoagent',
            field=models.BooleanField(default=False, verbose_name='Иноагент'),
        ),
    ]
