# Generated by Django 4.1.2 on 2022-10-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_role_options_artilce_inoagent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artilce',
            name='inoagent',
        ),
        migrations.AddField(
            model_name='artilce',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на статью'),
        ),
        migrations.AddField(
            model_name='media',
            name='inoagent',
            field=models.BooleanField(default=False, verbose_name='Иноагент'),
        ),
    ]
